id: AA1334727
title: 'Ocean of Offering Clouds: A Light Offering Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:22:46.637484
  last_modified_at: 2022-02-28 23:22:46.637493
