id: AA1334727
title: Praise of Kunga Yeshe, Great Being and Master of Extensive Scriptural Traditions
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:22:46.640952
  last_modified_at: 2022-02-28 23:22:46.640961
