id: AA1334727
title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:22:46.643007
  last_modified_at: 2022-02-28 23:22:46.643013
