id: AA1334727
title: Supplement to the Lineage Prayer for the Lamdré Instructions Composed by Tsarchen
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:22:46.648530
  last_modified_at: 2022-02-28 23:22:46.648537
