id: AA1334727
title: 'The Heart of the Mahāyāna Path: A Bodhisattva’s Prayer of Aspiration'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:22:46.651279
  last_modified_at: 2022-02-28 23:22:46.651283
